### ISSUE TITLE
setUp/tearDown should be only called once per group

### ISSUE THREAD

**Issue by zoechi** [dart-lang/unittest#17]
when I have
```
main
   group
     setUp
     tearDown
     test1
     test2
     testx
```
it's executed like

- setUp
- test1
- tearDown
- setUp
- test2
- tearDown
- setUp
- testx
- tearDown

This doesn't make sense. For such a behavior I can just use plain functions and call them from within testx.

When I need to start a server before running a group of tests and shut the server down after all test are finished, I don't see a way to do this in the current unittest implementation (stable and 0.12.0-alpha.0)

**Comment by nex3** [comment]
The current behavior is the same as what `unittest` has always done, and what most other test frameworks use "set up" to refer to. I think it's also more robust behavior in general: there's better test isolation when the test cases don't share state or resources. Otherwise it's easy for an error in one test to cascade and cause errors in other tests as well. In all the tests I've written, I've been very happy setting up and tearing down a new server for each test.

That said, it looks like other function-style test runners like RSpec and Jasmine do support a means of doing some work at the beginning of their notions of a group, so maybe there's something to it. I'd be willing to consider adding `setUpAll`/`tearDownAll` functions given a compelling use-case.
